### ISSUE TITLE
Edit photo on ‘Edit profile’ page 

### ISSUE THREAD

**Issue by MartaLytvynovuch** [ita-social-projects/GreenCity#1006]
As a Logged User, I want to edit my photo on my ‘My habits’ page.

**Acceptance criteria:**
1. On the "Edit Profile" page, If the User has not yet uploaded an avatar, display the default photo, if the user has already changed it, display the uploaded photo.
2. When the user clicks on the icon "Add a photo" in the system, the pop-up where we have the image is opened, message: "Do you want to change your profile picture?" and two buttons: "Cancel", "Upload new photo".
3. When the user clicks on the "Cancel" button, the system comes back to the "Edit profile" page.
4. When the user clicks on the "Upload new photo" button, the file system of the user's computer is opened, where he/she selects a photo.
5. When the image has been downloaded, the frame can be moved by the User with the help of a cursor/mouse and can be fixed on the needed segment.
6. Photo size should be 148*148.
7.The buttons change to "Change photo" and "Save photo".
8. When the user clicks on the "Save photo" button, the system comes back to "Edit profile" and the photo will be changed in the system.
9. When the user clicks on the "Change photo" button, the file system of the user's computer is opened, where he/she selects a photo again.
10. When the user finishes editing the photo, he/she will have an avatar. 

User Story: [GC-1415](https://jira.softserve.academy/browse/GC-1415)
Change request: #1303 

**Tasks**

- [x] Download the user's avatar on the Edit Profile page.

- [x] Add pop-up for edit photo;
- [x] Add file loader for photo;

- [x] Add photo cropping functionality;

- [x] Save changes on backend;

- [x] Save changes on UI;

- [x]  Pull request;

- [x]  Merge;

**API**
https://greencity.azurewebsites.net/patch/user/profilePicture

Example Value:
{
  "id": 0,
  "profilePicturePath": "string"
}

**Mockup**

![2020-08-31 (1)](https://user-images.githubusercontent.com/62401277/91727822-e197a180-ebaa-11ea-958a-767230d34a40.png)
![2020-08-31](https://user-images.githubusercontent.com/62401277/91727829-e3616500-ebaa-11ea-85d4-3121a65d81d1.png)
