### ISSUE TITLE
Add social network on my profile on ‘My habits’ page 

### ISSUE THREAD

**Issue by MartaLytvynovuch** [ita-social-projects/GreenCity#1007]
As a Logged User I want to add social networks and edit profiles on the ‘My habits’ page.
![Знімок екрана 2020-07-14 о 22 20 03](https://user-images.githubusercontent.com/65448781/88525080-d2995e80-d002-11ea-9c39-d2fba5c72977.png)

**Acceptance criteria:**
**1.** 'Linked social networks' module is not mandatory.
2. When the user clicks the Edit icon, he/she is directed to the filled-out Edit profile form, where he/she has a possibility to add, edit, delete social network.
**3.** Logged user can add two or more accounts from one social networks. 
**4.** Logged user can't add more then 5 social networks.
5. When users add, edit, delete social networks users should have a possibility to save the selected area or Cancel the selection.
6. When the user clicks the ‘Save’ button, the social networks will change in the system.
7. When  the user clicks the ‘Cancel’ button, the social networks will not change in the system
8. A link for the social network should be enabled. 
9. When we click on an icon of social networks we go do this page.

User story:  [GC-1489](https://jira.softserve.academy/browse/GC-1489)
Change request #1298, #1340 

### Tasks:

1. [x] Create UI (markup and styles from mockup); (Julia) #1011 
2. [x] Create BL (necessary CRUD methods for social networks, relations with parent component); (Roman)
3. [x] Show social networks in profile;
4. [x] Pull request;
5. [x] Merge;

**Comment by SolkaNik** [comment]
**Test design for web**

1. [Edit profile] Profile without social networks can be saved (*icons does not display on the profile page)
2. [Edit profile] User can add to profile two and more links from one social network
3. [Edit profile] User can add up to five social network links to profile
4. [Edit profile] User cannot add more than 5 social network links to profile
5. [Edit profile] After clicking ‘Cancel’ button last edits in ‘Social network’ module are not saved (*related to #1009)
6. [Edit profile] User can edit social network links
7. [Edit profile] User can delete social network links (*waiting for approvement about confirmation message)
8. [My habits] The icons of social network on ‘Profile’ module are clickable
9. [My habits] The icon of social network on ‘Profile’ module has the hover with full link to account
10. [Edit profile] ‘Add social network’ module UI (related to #1011)
11. [Edit profile] En localization of module
12. [Edit profile] Uk localization of module
13. [Edit profile] Ru localization of module

**Test design for API**

1. [API] [Edit profile] User can add to profile two and more links from one social network
2. [API] [Edit profile] User can add up to five social network links to profile
3. [API] [Edit profile] User cannot add more than 5 social network links to profile
4. [API] [Edit profile] User can edit social network links
5. [API] [Edit profile] User can delete social network links
6. [API] [My habits] The icons of social network on ‘Profile’ module are clickable
