### ISSUE TITLE
BL for shopping list

### ISSUE THREAD

**Issue by HryshkoAnton** [ita-social-projects/GreenCity#1101]
### Summary
As a user I want to see my "Shopping list" on the Profile Page

### Acceptance Criteria
1) As a authorized user you can see the number of your Shopping list items;
2) As a authorized user you can see all your Active Shopping items;
3) While shopping list is loading, user can see the spinner;
 Logic of clicking at 'See all' button and checkboxes does not included in this task.

### Tasks
 

- [x] load shopping list from API

 

- [x] display count of shopping list items, button "see all" and three favorite items;

- [x] if user does not have any shopping items, show message "you have no items in your shopping list";

- [x] while shopping list is loading, show spinner;

- [x] pull request;

- [x] merge;

**API**
https://greencity.azurewebsites.net/goals/shoppingList/1601/language/en

**Comment by HryshkoAnton** [comment]
![image](https://user-images.githubusercontent.com/45083515/89649571-ab2b7700-d8c9-11ea-9e40-46b9ac115b3b.png)
