### ISSUE TITLE
BL for shoppinglist's checkboxes

### ISSUE THREAD

**Issue by HryshkoAnton** [ita-social-projects/GreenCity#1166]
### Summary
As a user I want to edit the status of my shoppinglist item to 'DONE' or 'ACTIVE' clicking on checkboxes.

### Acceptance Criteria

If the user clicks on the checkbox to the right of the item, the item's status will be toggled.
If previous item's status was "DONE", it will change on "ACTIVE", and checkbox will become unchecked.
If previous item's status was "ACTIVE", it will change on "DONE", and checkbox will become checked.
If user refresh the page, this changes will stay.

**Tasks**

- [x] make patch request to API

- [x] save changes on backend

- [x] save changes on UI

- [x] pull request

- [x] merge

**API**
https://greencity.azurewebsites.net/goals/shoppingList/1601?goalId=3&status=true
