### ISSUE TITLE
UI for calendar on 768px view

### ISSUE THREAD

**Issue by sofiiamatsyhin** [ita-social-projects/GreenCity#1178]
As a user, I want to see Calendar so that I will be able to view date(day, name of day, week, month and year).

**Acceptance criteria:**

1. The default calendar view is a week-view.
2. User can see current date.

<img width="500" alt="Screen Shot 2020-08-18 at 16 28 21" src="https://user-images.githubusercontent.com/55846203/90519270-7bedf300-e170-11ea-8330-063e9397e763.png">

**Tasks**

- [x] Create new component for calendar
- [x] Create HTML for calendar
- [x] Add style for component 
- [x] Pull request 
- [x] Merge
