### ISSUE TITLE
Change requests

### ISSUE THREAD

**Issue by SolkaNik** [ita-social-projects/GreenCity#1270]
- [x] Error messages for image, name, city, credo (API & web). #1010 

- [x] Upload photo from Google, Facebook, etc.

- [x] User can drop photo from the folder.

- [x] Profile privacy - default value is 'checked'. #1008 

- [x] See the 'Social network' page name while hovering the icon. #1007 

- [x] Forbidden characters for 'City' field.  [#1254](https://github.com/ita-social-projects/GreenCity/issues/1254)

- [x] When user does not have social networks, the icons of social networks does not display on the profile page. #1007 

- [x] If user has 5 social networks the button 'Add social network' doesn't display OR the button is disabled. #1007
