### ISSUE TITLE
[Achievements]

### ISSUE THREAD

**Issue by forestik** [ita-social-projects/GreenCity#1894]
**As a** developer **I want to** create achievements **so that** users can track their achievements

**Description**
This is an Epic with the goal to create achievements

### Tasks 
1. [x] Create an admin page for achievements. #1895 
2. [x] Create a table that contains data that will be used to calculate achievements. #1901 
3. [x] Migrate data to a table that contains data that will be used to calculate achievements. #1962 
4. [x] Writing logic to calculate achievements. #1996 
5. [x] All created achievements must be added to new users #1997 
6. [x] Add method that find all achievements curent user with status acvite and not notified #2091
