### ISSUE TITLE
Create user personal page on Admin

### ISSUE THREAD

**Issue by KwintiukN** [ita-social-projects/GreenCity#2887]
**Create user personal management page on Admin.**

### Mockup:
![image](https://user-images.githubusercontent.com/83454713/125162560-4475a400-e191-11eb-8ab6-8da6fd623c27.png)
### Tasks:
- [x] Create controller that returns user personal page
- [x] Create thymeleaf template for page
- [x] Create neccessary services and repositories
- [x] Add tests
### Functionality not available yet:
• Achievements pictures
![image](https://user-images.githubusercontent.com/83454713/125162912-345ec400-e193-11eb-9b68-f53dc471faf4.png)
• Created Events table
• Actions button in Custom Habits table
![image](https://user-images.githubusercontent.com/83454713/125162939-64a66280-e193-11eb-8d91-1c49c4ae0aad.png)

**Comment by maru0909** [comment]
Nothing to test
