### ISSUE TITLE
Epic: Comments refactoring

### ISSUE THREAD

**Issue by df7734** [ita-social-projects/GreenCity#7437]
### The goal of this refactoring is to bring the Comments entity to a **universal state, eliminating unnecessary services, tables in DB and DTOs**.

**Current situation:** 

- EventComment entity, events_comment in DB, EventCommentService + Impl + Repo, 6 DTOs
- EcoNewsComment entity, econews_comment in DB, EcoNewsCommentService + Impl + Repo, 6 DTOs
- **HabitCommentController already on new universal service (CommentService) and DB table (comments)**

**Tasks connected to this feature:**

https://github.com/ita-social-projects/GreenCity/issues/7371
https://github.com/ita-social-projects/GreenCity/issues/7327

**Tasks to be done:**

- [x] CommentService now doesn't have notification for tagging and all other notifications, notification themselves work with mistakes.
- [x] Optionally (comments on the site are mostly written as a part of testing and don't contain meaningful information, maybe we don't need them, you should clarify this with mentors): move data from events_comment and econews_comment tables to comments table, **think about how to keep binding of replied IDs. While moving you have to set article_type.** 
- [x] Make sure that all the functionality of EventComment and EcoNewsComment services is reproduced in CommentService (e. g. Tagging functionality from EcoNewsCommentService)
- [x] Remove EcoNewsComment and EventComment entities, services, impls, repos, DTOs, tables in DB.

Final state: 

- **Different controllers for comments** (EventCommentController, EcoNewsCommentController, HabitCommentController)
- **Same** CommentService, CommentServiceImpl
- **Universal** comment DTOs
- **One** table in DB (comments)
- Everithing is **up-to-date with front-end side** (some mappings in controller should be refactored, my vision of naming is in HabitCommentController)
